# This is a basic workflow to help you get started with Actions

name: CI_DEV

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "develop" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  check_init:
    runs-on: ubuntu-latest
    if: ${{ contains(github.event.head_commit.message, '[INIT]') }}
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: SSH Remote Commands
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{ secrets.DEV_SSH_HOST }}
          username: ${{ secrets.DEV_USERNAME }}
          key: ${{ secrets.DEV_PEM_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            whoami
            apt-get update
            apt-get install git -y
            git clone https://github.com/BiBimBapXOpenStack/team1-imageboard.git
            cd team1-imageboard/bin
            sudo chmod 755 setup.sh
            ./setup.sh ${{ secrets.DB_URL }} ${{ secrets.DB_USERNAME }} ${{ secrets.DB_PASSWORD }} ${{ secrets.JWT_KEY }}
            
            
      
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: SSH Remote Commands
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{ secrets.DEV_SSH_HOST }}
          username: ${{ secrets.DEV_USERNAME }}
          key: ${{ secrets.DEV_PEM_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            whoami
            ./team1-imageboard/bin/pull.sh
        
